### ISSUE TITLE
MissingMethodException trying to instantiate client.

### ISSUE THREAD

**Issue by Myvryn** [manybrain/mailinator-csharp-client#1]
I pretty much copy-pasted the example for FetchInboxRequest. However, I never get to the point where I'm actually trying to fetch the inbox. 

The call to instantiate the MailinatorClient object results in a MissingMethodException. 
Method not found: 'Void RestSharp.RestClient.set_Timeout(Int32)'.

`MailinatorClient mailinatorClient = new MailinatorClient(MailinatorApiTokenKey);`

Where MailinatorApiTokenKey is set to the API Token displayed in my Teams Settings page
![image](https://user-images.githubusercontent.com/1087678/184244145-dd4ae4f6-5f33-4936-9055-3e6e083c2d5f.png)

This is about as basic as you can get in terms of potential things to screw up ... But I've been known to screw up easier things.  
Am I missing something here?

**Comment by marianmelnychuk** [comment]
Hello. It seems like the problem is because another solution you are using within the same directory is using RestSharp 107 and Mailinator uses 106 which is not compatible with 107 and you can only use one version in your project.

I have pushed a new version of code (also updated Nuget package to 1.0.2) where migrated our API to RestSharp 108 version. 
Please try to use this new package and let me know if it works.

Thanks,
Marian

**Comment by Myvryn** [comment]
Thanks for the update. 
For the moment, I was able to get what I needed by hitting the API directly with RestSharp.  



I’ll take a look at your latest push and see if I can get rid of what the stuff I wrote. 

 

Eddy

**Comment by Myvryn** [comment]
Verified your change fixed the issue that I was seeing.  
Thanks for the fast turn around..
